alpheios-project/alpheios_nemo_ui

alpheios_nemo_ui/__init__.py
this change in my prior commit broke some of the texts, so putting it back the way it was
=> fix grouping in book/poem/line

alpheios_nemo_ui/data/templates/alpheios/login.html
For the https://github.com/alpheios-project/alpheios_nemo_ui/issues/76#issuecomment-487123889
Very small PR - merge without review.
=> Remove email from login

alpheios_nemo_ui/data/templates/alpheios/copyrightpopup.html
this text eventually needs to move into a i18n messages file along with the rest of the ui text but for now it will just go in the template.
=> update copyright text

alpheios_nemo_ui/data/templates/alpheios/navcollection.html, alpheios_nemo_ui/data/templates/alpheios/navreferences.html
@irina060981 just FYI - I'm removing the search box from collections and references for now. this won't be implemented in time for the beta.  Will go ahead and merge as it's a minor change.
=> remove the find box for now

app.py
just an FYI PR, adding some greek texts, and removing the arabic collection for now because it won't be part of the beta.
=> add greek texts, remove arabic for now

alpheios_nemo_ui/data/templates/alpheios/bibliogpopup.html
fyi, minor fix, will merge without review
=> fix passage xml link

alpheios_nemo_ui/data/assets/js/infinite-scroll.js
For the https://github.com/alpheios-project/alpheios_nemo_ui/issues/53
=> Fix visibility for breadcrumbs arrows

alpheios_nemo_ui/data/templates/main/container.html
For the issue https://github.com/alpheios-project/alpheios_nemo_ui/issues/203
@balmas , It is really very small - I will merge it without a review.
=> Remove font-awesome import

alpheios_nemo_ui/data/templates/alpheios/collection-item-card_full.html, alpheios_nemo_ui/data/templates/alpheios/helppopup.html, alpheios_nemo_ui/data/templates/alpheios/navreader.html, alpheios_nemo_ui/data/templates/alpheios/navreferences.html
text change only, no code. will merge without review.
=> fix #187 - renamed browse to toc

alpheios_nemo_ui/data/assets/static/xslt/alpheios-enhanced.xsl
for #207 - very minor change will merge.
=> fix creative commons url

alpheios_nemo_ui/data/templates/main/container.html
pass authentication environment to embedded library
alpheios-project/components#685
requires alpheios-project/embed-lib#78
=> pass auth env to embedded lib

alpheios_nemo_ui/data/templates/main/container.html
=> textLangCode can't be a const

alpheios_nemo_ui/data/templates/main/container.html
positioning action panel closer to the top
merging without review for testing
=> for alpheios-project/components#703

alpheios_nemo_ui/data/templates/alpheios/helppopup.html
#264 and #259
merging without review - text change only.
=> fix help text

alpheios_nemo_ui/data/assets/static/xslt/alpheios-enhanced.xsl, alpheios_nemo_ui/data/templates/main/container.html
=> segment the homer treebanks by book

alpheios_nemo_ui/data/templates/alpheios/navreader.html
=> hide the toc rather than disable it

alpheios_nemo_ui/__init__.py
to explore whether we can offer navigation to first/last passage, adding a lastpassage route. no ui so far.
=> Issue 267 fix2

alpheios_nemo_ui/data/templates/alpheios/login.html
Small fix https://github.com/alpheios-project/alpheios_nemo_ui/issues/280
=> Change text for login on the main menu

alpheios_nemo_ui/__init__.py, alpheios_nemo_ui/data/templates/alpheios/breadcrumbtext.html
show only single citation as example in find passage placeholder
also group book/poem/line scheme by line not poem
=> fix for #285

alpheios_nemo_ui/__init__.py
A small update for the Nemo UI to send an expiration date to its clients (for alpheios-project/webextension#244)
=> Webext i244 token expiration
